### ISSUE TITLE
Remove disentangle option from add/edit taxon form

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/classic#105]
Remove "If this is more than one taxon, you may disentangle them" from this form as this functionality is no longer supported

**Comment by mclapham** [comment]
Better yet - support this functionality! I know of several taxa that need to be disentangled: Angulithes mermeti / Angulithes triangularis for example (this taxon pair also suffers from the "original name bug" https://github.com/paleobiodb/classic/issues/62#issuecomment-333931236).
