### ISSUE TITLE
Remove preservation category check for extant taxonomic names

### ISSUE THREAD

**Issue by mclapham** [paleobiodb/classic#119]
Currently the taxonomic name entry will only allow you to mark a taxon as extant if the type if either body or amber. However, there are some higher taxonomic groups (like the subfamily Juralydinae) described from compression fossils but later recognized to contain extant species as well, but I can't select "compression" as preservation category and "yes" for extant. This check doesn't seem to serve much purpose.

**Comment by mmcclenn** [comment]
Removed this check.
