### ISSUE TITLE
THE 387 BUG

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/classic#12]
The issue which will not die :)

The count should represent the total number of Authorizers who are alive and have active accounts.

**Comment by markuhen** [comment]
Upon reflection, I want this number to be the number of Authorizers + Enterers who are flagged as Active in the active field.

**Comment by markuhen** [comment]
Upon further reflection, let's make this number to be the number of Authorizers + Enterers. Period. The text on the page will be changed to say "contributors" instead of "scientists".

**Comment by markuhen** [comment]
Julian, Valerie: Hasn't this been resolved? If so, please close.

**Comment by mmcclenn** [comment]
I wrote some code to fix this, but got pulled off onto other issues and didn't finish merging it into the main branch. I will get to this soon, after I finish my current work on the data acquisition API.
