### ISSUE TITLE
Download form 500 Server Error

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#122]
See screen captures to see what conditions trigger the error.

![pastedimage](https://user-images.githubusercontent.com/19557452/38428583-21cac26c-398a-11e8-8898-66dbb1731418.png)
![pastedimage-1](https://user-images.githubusercontent.com/19557452/38428588-2309669c-398a-11e8-95d7-b9bef5a2d667.png)

**Comment by jpjenk** [comment]
@mmcclenn, I've traced the fault, it is a data service error attributable only to the lithology filters.

DBD::mysql::st execute failed: Unknown column 'cl.lith_type' in 'where clause' at /Library/WebServer/pbdb-new/lib/PB2/SpecimenData.pm line 858.

**Comment by markuhen** [comment]
Julian,

Thank you!

Mark

On 4/6/18 12:05 PM, Julian Jenkins wrote:
> @mmcclenn 
> <https://secure-web.cisco.com/1miGTW3jPZRWWsaUb7RpvVDYY9suGQMI2-OKm5srRjTSdgXGKrTxhH2UZU6H8WBAIg1L0jbP1UW3fwBbLxjyiHBu3QLEjaz9p3OgZcjN9vUILNf7xvCeeWddhJdEUNdNA4eoil4r3oIK09HTsQhoE71XaJirG97lcB3xvll9KSZXjJms-orL8w-W4A7hd3hFx65Ur30X4cXX6cfvsFTf2s2QXscwvtnrXw0JUKQI6hZP5x1FpMP3-51Fka8p_uUgxbydVU25TiM7pZgx-RapfHjdiCt2UBTIBfZWsKWuuO27UZnKT5u3wMr1fh6-Q6qesTwxFlGdK9KF37AbWG29jXMc_-dYuCJ-aWgm9mv-U-2jipEBvxLdxAsxG3n_V6PtqOmy0Y76SMsr3QYmgc-0-N3aZCI9H5llj0rGM3LUN8sqT3QMSZdgFCFydO_ktxvuq/https%3A%2F%2Fgithub.com%2Fmmcclenn>, 
> I've traced the fault, it is a data service error attributable only to 
> the lithology filters.
> 
> DBD::mysql::st execute failed: Unknown column 'cl.lith_type' in 'where 
> clause' at /Library/WebServer/pbdb-new/lib/PB2/SpecimenData.pm line 858.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1GBSm5ESgGN7Ls5wjAflz0FknhYaWn3AAcP2mpIhjvcvLYa9c-HwBnRGNlMKLYhnlJUbnGInmhh0Z0Hqc59J-tU42aij1rC0Unsiel1CY3gGtkU8MCZxuIOCZFLIeO5hLt6FPUwtQqLWohDpUDZcm3pi__SorDb2c9FXkmCd9lBMPM6e59JrGIdD5DJMFtPYj7cBSU6D1VWCdcrPk9qqozfoL7AeJXgw5MkVh1IsLY-BjOnDeAAu44m0eQlx6KXbnm7Q7Rj1GrZENxJ1knJTH7CEgzPN0aAp2D2blhGTjTm30K004mCfsVBi5c47qjq0SrnFyPT4pOjVgUx4EhBc6HQh3v87iWpelOYkJY1hAmZems1Y4FLAcbUhFaTrB8nO0YQD5_WW-GLZO0LUTNNsUF5HQ73V3uukS-pgljuDV2_BLZReV89lwhT-XgFvNjX7u/https%3A%2F%2Fgithub.com%2Fpaleobiodb%2Fclassic%2Fissues%2F122%23issuecomment-379300039>, 
> or mute the thread 
> <https://secure-web.cisco.com/1E-grfK34vSCFXW7yim7VCwVvGscCIAnfLo4PiyBQ1JeWVPN6r6VGqB_cZEsYVBYBU6oJnHxKoZx5ERVXHVpJKi4hA58Qa-t-GvFKQd2NoS1YyDQn3pA9hNIf6lTq0QCoHhMpSO3QF5LUPp79QEIifNSJSwayWP9q96fyADBdDTJyfNTeSR1Scb4uO_I84Lxg6GrEjMHMp8j2nZJjXLkUY8IVAR-Y2ozrMPFZtLG1WAjAGO2s-_UB7eK6e46UctD45ASJShcP7PUGqpuNCsUyTEAytgUMlpKOlF74TV7FILJUWKoL11HiTYurcgBM9yj3Qx7HrbHIn-qAfUNKRqlC_Q_jrX9J8QRXmjOC1brIcP1BWaEV0K4fZemAQmCCHbcRPMMuVNogJQEYeexHeuaa4Af-KSryaMnTWAb2vjcmlSh6epY3WkYmjwb_LqNTYLsG/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASpsTF7Yzp0B_MNlOcdl-Fv_eILzKnv1ks5tl5JYgaJpZM4TKNDP>.
> 

-- 
Mark D. Uhen
Associate Professor & Associate Chair
George Mason University
AOES Geology
MSN 6E2
Fairfax, VA 22030
Phone: 703-993-5264
Fax: 703-993-3535

**Comment by markuhen** [comment]
This also happens when you try to download taxa entered after a certain date.

**Comment by mmcclenn** [comment]
This was fixed a long time agao.
