### ISSUE TITLE
Wishlist: Add a ZooBank field in Reference, Taxon Authority Data, and Opinion pages

### ISSUE THREAD

**Issue by evlacho** [paleobiodb/classic#140]
Hi there. I do not know if this is the proper way to leave a comment about possible features for the future (wishlist). This is NOT urgent.

Issue: Since the last amendment of the Zoological Code (ICZN) which allowed publications in e-only journals, the database Zoobank (http://zoobank.org/) was created to register works and taxon names. Each work  and each new taxon name have their own identifier (also in the future the same will happen for the nomenclatural acts), called LSIDs, which look like this: LSID. urn:lsid:zoobank.org:act:4F970E7F-2344-47AD-9956-07052F2FE12E

Current status: I currently add this information in the comments field for any particular case.

Idea: It might desirable to add a new, specific, field that has to do with the LSIDs or other kinds of registration information (I do not know if in other disciplines they do the same). Having this information in specific and separate fields will help as well in downloading this kind of valuable information. 

Also, we could even connect the LSIDs as links with the specific ZooBank page in the same way we do with other external databases.

Thanks in advance for your attention. This is not urgent

**Comment by markuhen** [comment]
Add to PBDB 2.0
