### ISSUE TITLE
Age range and collections contains extraneous and strange information

### ISSUE THREAD

**Issue by evlacho** [paleobiodb/classic#149]
When I am on the Full Details of a specific taxon, and I click on the "Age Range and Collections" tab, there are many collections listed there that have, apparently, nothing to do with the taxon.

For example, the Chelonoidis gringorum taxon lists 76 collections and many have nothing to do with it. Some are are just indet. occurrences of this genus, whereas there are others (e.g., the collection 167274) that have nothing to do at all with this taxon.

Then, these collections are used to calculate the age range, which could lead to false estimations.

It looks like that the page on Chelonoidis gringorum contains all or most collections that contain Chelonoidis (different species and sp.), as well as collections containing some sister or more distant-related clades (e.g., Geochelone and Homopus).

**Comment by markuhen** [comment]
I just looked at Chelonoides gringorum and only see 40 collections. 167274 is not one of them. I'm not sure why this is inconsistent, but that in itself is a problem.

**Comment by evlacho** [comment]
OK, you are right. Now it is correct, but yesterday (at the moment when I wrote it here) it was different (no screenshot...).

I have been updating the opinions (mostly adding the diagnoses and page references), and perhaps it got a bit confused? I do not know. But right now it seems fine.

**Comment by mclapham** [comment]
Yes, sometimes opinions don't get sorted out until (I presume) a script runs overnight to clean everything up. You can see the same behavior if you look at the print taxonomic hierarchy option after entering a bunch of opinions - it's often jumbled initially but then sorts itself out.

**Comment by mmcclenn** [comment]
Unfortunately, the routine that updates the taxonomy table screws up sometimes. It then gets automatically corrected by the nightly table rebuild. According to the error messages I got over the weekend, that appears to be what happened.
