### ISSUE TITLE
Collection name search seems to fail when you copy and paste names with punctuation from PDFs

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#179]
See Jim’s Jaw Site for example.

**Comment by markuhen** [comment]
[Worthy & Boles 2011.pdf](https://github.com/paleobiodb/classic/files/5484032/Worthy.Boles.2011.pdf)

**Comment by mmcclenn** [comment]
I fixed this problem on dev.paleobiodb.org. Mark, can you please test this? Do all kinds of collection name searches, and let me know if any unexpectedly fail.
