### ISSUE TITLE
Duplicate Reference Search Form searches only the first two authors, not all authors

### ISSUE THREAD

**Issue by evlacho** [paleobiodb/classic#197]
Duplicate Reference Search Form (before adding a new reference) searches only the first two author last names fields, but not the names of authors in the additional text field.

This might lead to duplicate references.

I would suggest to expand the search to all names fields as well.

**Comment by mclapham** [comment]
You have to use "include" rather than "equals" in the dropdown to search that field. Because that field is a string that includes the initials (and potentially multiple names), one last name will never equal everything in the field.
