### ISSUE TITLE
Time binning missing in downloaded data

### ISSUE THREAD

**Issue by evlacho** [paleobiodb/classic#200]
I noticed that when I download data and select time binning, instead of data only dashes appear.

**Comment by mmcclenn** [comment]
Thanks for catching this! My recent update to the time interval system broke that functionality, and I hadn't realized that. It is now fixed.

**Comment by evlacho** [comment]
Hi mmcclenn, it seems that it happens again, I try to download data today and time binning is missing!

Thanks in advance,
Evan

**Comment by mmcclenn** [comment]
I'm not sure what happened, but apparently my fix was somehow reversed. I have now fixed this again, and it should stay fixed at this point.
