### ISSUE TITLE
Occurrence page should allow reidentifications same as original ID

### ISSUE THREAD

**Issue by mclapham** [paleobiodb/classic#202]
Sometimes an occurrence is reidentified, but then a subsequent author reidentifies it back to the original name. When editing the occurrence list (for example to add an additional occurrence from another reference), the entry form gives an alert "Taxon and its ReID have the same name" and will not allow the form to be submitted. However, it's fine for a taxon to be reidentified back to the original occurrence name.

**Comment by mmcclenn** [comment]
This is now fixed. An occurrence list with an occurrence reidentified back to the original name can now be saved.
