### ISSUE TITLE
Quick search fails, logged in or not

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#71]
When you use quick search, it fails with this error:

Server Error
Please contact the database administrator

**Comment by markuhen** [comment]
Quick search works on the splash page, but no where else. It should work like it does on the splash page everywhere.

Also, it should be searching for people, but it does not do that on the splash page either.

**Comment by jpjenk** [comment]
Quick Search is now fully functional so this issue is closing. However, issues remain with the CSS, this has moved to issue #90.
