### ISSUE TITLE
Bad link in Reference summary

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#73]
See the attached image below. When you click on 4 taxonomic opinions, it should show a clickable list of those 4 opinions. Instead, it shows the 2 taxa entered from this paper. This link needs to be updated.

![meng](https://user-images.githubusercontent.com/19557452/29432796-e8ab8bd6-836a-11e7-8fb7-f1967c95d867.jpeg)

**Comment by jpjenk** [comment]
Fixed
