### ISSUE TITLE
Homonym warning not displaying correctly

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#85]
![homonym warning](https://user-images.githubusercontent.com/19557452/30662584-8dac34cc-9e15-11e7-964e-7ba7ed32f85b.jpg)

**Comment by mmcclenn** [comment]
What is it supposed to be doing differently?

**Comment by markuhen** [comment]
Well, It should look like every other warning we give. This one is smack up against the left margin, way off from the centered text below.
