### ISSUE TITLE
Taxon entry form won't let me enter a subspecies in a subgenus.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#87]
See example below. This taxon is formatted just fine. It is a subspecies in a subgenus.

![subgenus subspecies](https://user-images.githubusercontent.com/19557452/30923295-786be242-a379-11e7-81fd-4f59632dc533.jpeg)

**Comment by mclapham** [comment]
The workaround for this is to search for the name without subgenus (in this case enter Otolithus toulai cristasa) and then add the subgenus to the name when it brings up the taxon entry form.

**Comment by markuhen** [comment]
Fixed by Michael.
