### ISSUE TITLE
Reference entry restriction needs to be removed

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#88]
Please remove the reference entry restriction that requires a title to end with a letter. This is simply not true, as you can see in the image below. Let's just make this a warning instead.

![period](https://user-images.githubusercontent.com/19557452/31734697-92d218fa-b40d-11e7-8dde-d8a251bd5d8d.jpeg)

**Comment by jpjenk** [comment]
Fixed in the frontend code
