### ISSUE TITLE
Occasional crashing of Wing toolkit REST server

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/classic#97]
Suspect this may be due to attempts to load inactive services.

**Comment by jpjenk** [comment]
Menu choices are presented within the Admin interface which use the async job queue runner beanstalkd (and its interface, wingman). Because these services are not activated, selecting these tools will hang the internal rest api. Currently we do not require these advanced services so I have disabled the menubar on the Accounts and Admin panels.

**Comment by markuhen** [comment]
This happened again on December 13 (or perhaps earlier).

**Comment by markuhen** [comment]
I guess this is fixed?
